// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvevjed9bAu1KhnW7kcJBznr2OBCjL33s',
    appId: '1:584850925629:web:7b09d88bef8e3b3703a254',
    messagingSenderId: '584850925629',
    projectId: 'parkinson-app-rbt',
    authDomain: 'parkinson-app-rbt.firebaseapp.com',
    storageBucket: 'parkinson-app-rbt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpRCiDPxdujN1gBrCarnsKNvfRM7z0gsw',
    appId: '1:584850925629:android:3fde9ecb5d2944b603a254',
    messagingSenderId: '584850925629',
    projectId: 'parkinson-app-rbt',
    storageBucket: 'parkinson-app-rbt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCahtj54FOLj_17oDE2aSJqRnSR8JWN71Q',
    appId: '1:584850925629:ios:cb7a1137518fcf1303a254',
    messagingSenderId: '584850925629',
    projectId: 'parkinson-app-rbt',
    storageBucket: 'parkinson-app-rbt.firebasestorage.app',
    iosClientId: '584850925629-pf1kp7f4gt9sf1k81eifkgm0vuk8qsoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkinsonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCahtj54FOLj_17oDE2aSJqRnSR8JWN71Q',
    appId: '1:584850925629:ios:cb7a1137518fcf1303a254',
    messagingSenderId: '584850925629',
    projectId: 'parkinson-app-rbt',
    storageBucket: 'parkinson-app-rbt.firebasestorage.app',
    iosClientId: '584850925629-pf1kp7f4gt9sf1k81eifkgm0vuk8qsoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkinsonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvevjed9bAu1KhnW7kcJBznr2OBCjL33s',
    appId: '1:584850925629:web:b171dfbe6f445b6203a254',
    messagingSenderId: '584850925629',
    projectId: 'parkinson-app-rbt',
    authDomain: 'parkinson-app-rbt.firebaseapp.com',
    storageBucket: 'parkinson-app-rbt.firebasestorage.app',
  );
}
